readme: url typo edit
black7375/pretendard pull request #1
Opened 2022-06-12 01:36 UTC by kms0219kms

2022-06-12 01:37 UTC, kms0219kms commented
[orioncactus/pretendard#82](https://github.com/orioncactus/pretendard/pull/82) 에서 말씀드린 URL 수정 PR 드립니다.

2022-06-12 07:01 UTC, black7375 commented on packages/pretendard-jp/README.md
> +/>
여러줄이 아니라 계속 한줄로 유지가 되어야 한다고 생각합니다.

2022-06-12 07:02 UTC, black7375 commented on packages/pretendard-jp/README.md
> +@import url("https://unpkg.com/pretendard@1.3.3/dist/web/static/pretendard-jp.css");
`'` => `"`는 일관성 면에서 좋은것 같아요.

2022-06-12 07:04 UTC, black7375 commented on packages/pretendard-jp/README.md
> +@import url("https://unpkg.com/pretendard@1.3.3/dist/web/static/pretendard-jp-dynamic-subset.css");
jsdelivr 말고cdnjs나 unpkg에는 영향이 없는건가요?

2022-06-12 07:07 UTC, black7375 commented on packages/pretendard/docs/en/README.md
리스트 표시에 공백준게 이유가 있나 싶어서 놔두었습니다만, 특별한 사유가 없다면 PR처럼 바꾸는게 좋겠네요.

2022-06-12 07:11 UTC, black7375 commented on packages/pretendard/docs/ja/README.md
> +すべての機能を含む Pretendard を Web フォントとして使用するには、下記のコードを使用してください。使用する font-family 名は`Pretendard`です。
일본어는 제가 할 줄 몰라서ㅠㅠ
띄어쓰기 하는게 의도한건가요?

2022-06-12 07:22 UTC, black7375 requested changes
1. 다른 CDN에도 영향이 있는지 의논해봐야 할 것 같네요.
2. 여러줄은 한 줄로 바꾸는 것이 좋음.
3. 기타 포매팅은 좋아보여요.

2022-06-12 07:22 UTC, black7375 commented on packages/pretendard/docs/en/README.md
> +<details>
저도 HTML과  포매팅 측면에서 `/`를 제거하는게 좋다고 생각합니다.

2022-06-12 07:22 UTC, black7375 commented on packages/pretendard-jp/README.md
> +/>
여러줄이 아니라 계속 한줄로 유지가 되어야 한다고 생각합니다.

2022-06-12 07:22 UTC, black7375 commented on packages/pretendard-jp/README.md
> +@import url("https://unpkg.com/pretendard@1.3.3/dist/web/static/pretendard-jp.css");
`'` => `"`는 일관성 면에서 좋은것 같아요.

2022-06-12 07:22 UTC, black7375 commented on packages/pretendard-jp/README.md
> +@import url("https://unpkg.com/pretendard@1.3.3/dist/web/static/pretendard-jp-dynamic-subset.css");
jsdelivr 말고cdnjs나 unpkg에는 영향이 없는건가요?

2022-06-12 07:22 UTC, black7375 commented on packages/pretendard/docs/en/README.md
> +- [Pretendard Std](/packages/pretendard-std/docs/en/)
리스트 표시에 공백준게 이유가 있나 싶어서 놔두었습니다만, 특별한 사유가 없다면 PR처럼 바꾸는게 좋겠네요.

2022-06-12 07:22 UTC, black7375 commented on packages/pretendard/docs/ja/README.md
> +すべての機能を含む Pretendard を Web フォントとして使用するには、下記のコードを使用してください。使用する font-family 名は`Pretendard`です。
일본어는 제가 할 줄 몰라서ㅠㅠ
띄어쓰기 하는게 의도한건가요?

2022-06-12 07:22 UTC, black7375 commented on packages/pretendard/docs/ja/README.md
> +- [Yarn (recommended)](https://yarnpkg.com/package/pretendard)
`(recommended)`는 굳이 할 필요 없을것 같네요.
패키지 설치시 yarn에서만 동작하는 기능이 있는지 착각할 수도 있습니다.

2022-06-13 16:23 UTC, kms0219kms commented on packages/pretendard/docs/en/README.md
> +<details>
네 해당 부분은 단순 타이포 버그입니다. 저도 수정하느라 수정했는데 놓친게 있는군요. 감사합니다.

2022-06-13 16:24 UTC, kms0219kms commented on packages/pretendard-jp/README.md
> +/>
아 해당 부분은 제가 사용하는 prettier와 linter에서 자동으로 바꿔 놓은 부분인거 같네요. 한줄로 바꿔 주셔도 무관합니다.

2022-06-13 16:24 UTC, kms0219kms commented on packages/pretendard-jp/README.md
> +@import url("https://unpkg.com/pretendard@1.3.3/dist/web/static/pretendard-jp.css");
보통 css에서는 '를 주로 사용하는 편이라서 '로 표기했습니다.
"도 기능상 문제는 없습니다.

2022-06-13 16:24 UTC, kms0219kms commented on packages/pretendard-jp/README.md
> +@import url("https://unpkg.com/pretendard@1.3.3/dist/web/static/pretendard-jp-dynamic-subset.css");
네, npm배포 후 cdnjs의 PR만 통과되면 됩니다. unpkg는 영향이 아예 없습니다.

2022-06-13 16:25 UTC, kms0219kms commented on packages/pretendard/docs/en/README.md
> +- [Pretendard Std](/packages/pretendard-std/docs/en/)
특별한 사유는 없는 거로 알고있어요.

2022-06-13 16:27 UTC, kms0219kms commented on packages/pretendard/docs/ja/README.md
> +すべての機能を含む Pretendard を Web フォントとして使用するには、下記のコードを使用してください。使用する font-family 名は`Pretendard`です。
네, 한국말로 말하자면 아래와 같아져 수정했습니다.

```
모든기능을포함한Pretendard를Web폰트로사용하려면아래코드를사용하세요. 사용하는font-family이름은 Pretendard입니다.
```

이렇게 보니 이상해 보이는거 같아서, 실제 문서 가독성 측면에서 의도하여 입력하였습니다.

2022-06-13 16:27 UTC, kms0219kms commented on packages/pretendard/docs/ja/README.md
> +- [Yarn (recommended)](https://yarnpkg.com/package/pretendard)
아 네 알겠습니다.

2022-06-13 16:28 UTC, kms0219kms commented
제가 이 conversation 기능은 처음 사용해 보아 요청해 주신 request를 어떻게 적용하는지는 모르겠으나, 남겨드린 코멘트를 바탕으로 적용해 주시면 될 것 같습니다.

resolve로 표시되는 conversation도 열어가며 확인해 보세요.

2022-06-13 16:29 UTC, kms0219kms reviewed
제가 이 conversation 기능은 처음 사용해 보아 요청해 주신 request를 어떻게 적용하는지는 모르겠으나, 남겨드린 코멘트를 바탕으로 적용해 주시면 될 것 같습니다.

resolve로 표시되는 conversation도 열어가며 확인해 보세요.

2022-06-13 22:32 UTC, black7375 commented
Request 적용은 [`allpgs:monorepo`](https://github.com/allpgs/pretendard/tree/monorepo)에서  새로운 커밋을 해주시면 됩니다.

2022-06-16 00:13 UTC, black7375 commented
jsdelivr에서의 정책등까지 반영해서 한번에 업데이트 후 병합하도록 하겠습니다.

2022-06-17 00:29 UTC, black7375 commented
@kms0219kms 한번에 변경사항들을 볼 수 있게 https://github.com/allpgs/pretendard/pull/1
병합 가능하능할까요?

2022-06-18 13:34 UTC, black7375 approved these changes
일단 제 선에서 기본적인 준비는 된 것 같아요.
다른 분들에게 크로스체크를 받으면 되겠습니다.

2022-06-20 00:01 UTC, merged